version: '3'
services:
  backendserver:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - database
    command: >
      sh -c "sleep 4 && python manage.py migrate && gunicorn --workers=1 stroer_challenge.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DB_NAME: stroer_challenge
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_HOST: database
  database:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stroer_challenge